### ISSUE TITLE
Missing installation instruction?

### ISSUE THREAD

**Issue by bortzmeyer** [QratorLabs/measurement_tools#1]
In `INSTALL.md`, I think that one last command is missing, ` pip install . `, no? Otherwise, the tools are not installed. (I'm very bad at Python packaging so I do not dare to propose a PR.)

**Comment by bortzmeyer** [comment]
I see there is a  ` python setup.py install` mentioned in `README.md` but I was looking in `INSTALL.md`.

**Comment by euskov** [comment]
Indeed, the command was missing. We fixed INSTALL.md, added more detailed instructions, and we also added Dockerfile with complete setup.
